name: CI
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./scripts/gen_placeholders.sh
      - uses: actions/upload-artifact@v4
        with:
          name: dist-packs
          path: dist/*.gtpack
  doctor:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: dist-packs
          path: dist
      - run: |
          for p in dist/*.gtpack; do
            greentic-pack doctor --pack "$p"
          done
  smoke:
    runs-on: ubuntu-latest
    needs: [doctor]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: dist-packs
          path: dist
      - run: ./ci/smoke_deployer.sh
  publish:
    runs-on: ubuntu-latest
    needs: [smoke]
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist-packs
          path: dist
      - run: echo "TODO publish dist/*.gtpack to GHCR"
